# Generated by Django 5.1 on 2024-09-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=64)),
                ('resultCode', models.IntegerField()),
                ('resultDesc', models.TextField()),
                ('receiptNumber', models.CharField(blank=True, max_length=18, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('transactionDate', models.DateTimeField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
